typography_spectrum: 0.5987367075867951
color:
  brandStrength: 0.1481542717665434
  lightness: 0.2656552658881992
  saturation: 0.5346291018649936
  rhythmicContrast: 0.31121598626486957
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.5374248886946589
author:
  name: Ezri Carlebach
  email: ezri@starfleet.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dd245511-c277-40dc-833e-04a0b2d83ddb.png
name: ezri
title: 'Ezri Carlebach MPRCA FIIC FRSA Consultant, writer, lecturer'
